services:
  opengl-app:
    build: .
    container_name: opengl_container
    # Make the container privileged to ensure access to graphics hardware
    privileged: true
    environment:
      # Pass X11 display variable
      - DISPLAY=${DISPLAY}
      # Pass Wayland-specific variables
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    volumes:
      # Mount X11 socket
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Mount user's runtime directory for Wayland, PipeWire, etc.
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}:ro
