-- DAP configuration automatically generated by :GenLaunch on Thu Jun 19 16:50:23 2025
-- This file uses the PROJECT_DAP_CONFIGS table structure.

-- You can define project-specific adapters here if needed.
-- The global adapters at the time of generation are included below.
local dap = require('dap')
dap.adapters = {
  codelldb = {
    executable = {
      args = { "--port", "${port}" },
      command = "/home/yadard/.local/share/nvim/mason/bin/codelldb"
    },
    port = "${port}",
    type = "server"
  }
}

DAP_PRE_LAUNCH_TASK = "cmake --build build --config Debug"

-- This table holds all named debug configurations for the project.
-- The 'default' label is special: it will be loaded automatically on startup.
PROJECT_DAP_CONFIGS = {
  default = {
    cwd = "${workspaceFolder}",
    filetype = "cpp",
    label = "default",
    name = "Launch file",
    program = "${workspaceFolder}/bin/cache_simulator",
	args = {"32", "4", "1", "R", "1", "bin_1000.bin"},
    request = "launch",
    stopOnEntry = false,
    type = "codelldb"
  }
}
